"""Core PDF operations (local only): merge, split, extract, rotate, compress, etc.

Reliability: atomic writes, validation, same-path guards, disk preflight, lock retries.

Package layout:
  _core      shared IO / validation / transfer
  structure  merge/split/extract/…
  compress   size reduction
  transform  clean/encrypt/crop/nup/gray/images
  pagenum    stamp/renumber/flatten
  watch      folder batch helpers
"""
from __future__ import annotations

from leafkit.pdf_ops._core import (
    PAGE_SIZES,
    PasswordProvider,
    PdfOpsError,
    _assert_not_overwrite_inputs,
    _atomic_finalize,
    _box_tuple,
    _disk_free_bytes,
    _ensure_full_page_visible,
    _ensure_pdf,
    _estimate_size,
    _open_reader,
    _paths_equal,
    _preflight_disk,
    _resolve,
    _retry,
    _stamp_fitz_metadata,
    _stamp_writer_metadata,
    _temp_pdf_path,
    _transfer_pages,
    _unique_path,
    _validate_pdf_file,
    _warn,
    _write_writer,
    _writer_size_bytes,
    page_count,
    parse_page_range,
    take_warnings,
)
from leafkit.pdf_ops.compress import (
    COMPRESS_PRESETS,
    _compress_ghostscript,
    _compress_rerender,
    _kill_process_tree,
    _recompress_images_fitz,
    compress_pdf,
    find_ghostscript,
)
from leafkit.pdf_ops.pagenum import (
    WATCH_ACTIONS,
    _box_in_outer_margin,
    _collect_margin_content_boxes,
    _page_num_max_band,
    _page_num_probe_zone,
    _pick_stamp_xy,
    _rects_overlap,
    _renumber_cover_rect,
    _renumber_strip_height,
    add_page_numbers,
    flatten_forms,
    op_then_renumber,
    renumber_pages,
)
from leafkit.pdf_ops.structure import (
    _bookmark_split_indices,
    _fit_page_to_size,
    _split_by_size,
    _split_ranges,
    assemble_pages,
    create_blank_pdf,
    default_output_next_to,
    delete_pages,
    extract_pages,
    insert_blank_pages,
    insert_pages,
    merge_pdfs,
    mix_pdfs,
    reorder_pages,
    resize_pages,
    reverse_pages,
    rotate_pages,
    split_item_segments,
    split_pdf,
)
from leafkit.pdf_ops.transform import (
    _hard_crop_margins,
    _save_fitz_atomic,
    clean_metadata,
    crop_box,
    crop_margins,
    decrypt_pdf,
    encrypt_pdf,
    extract_text,
    extract_text_to_file,
    grayscale_pdf,
    images_to_pdf,
    nup_pdf,
    stamp_image,
)
from leafkit.pdf_ops.watch import list_watch_pdfs, watch_process_file

__all__ = [
    "PAGE_SIZES",
    "PasswordProvider",
    "PdfOpsError",
    "COMPRESS_PRESETS",
    "WATCH_ACTIONS",
    "page_count",
    "parse_page_range",
    "take_warnings",
    "merge_pdfs",
    "extract_pages",
    "delete_pages",
    "insert_pages",
    "insert_blank_pages",
    "create_blank_pdf",
    "mix_pdfs",
    "split_pdf",
    "split_item_segments",
    "rotate_pages",
    "default_output_next_to",
    "reorder_pages",
    "reverse_pages",
    "resize_pages",
    "assemble_pages",
    "find_ghostscript",
    "compress_pdf",
    "clean_metadata",
    "encrypt_pdf",
    "decrypt_pdf",
    "extract_text",
    "extract_text_to_file",
    "crop_margins",
    "crop_box",
    "nup_pdf",
    "grayscale_pdf",
    "images_to_pdf",
    "stamp_image",
    "add_page_numbers",
    "renumber_pages",
    "op_then_renumber",
    "flatten_forms",
    "watch_process_file",
    "list_watch_pdfs",
]
